server:
  port: 9999
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.151.99:3306/mybatis_test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver

#mysql8.0的配置为
#  spring:
#    datasource:
#      username: root
#      password: root
#      url: jdbc:mysql://192.168.151.99:3306/mybatis_test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
#      driver-class-name: com.mysql.cj.jdbc.Driver  #数据库驱动不同